### ISSUE TITLE
Problems with option 2

### ISSUE THREAD

**Issue by Hyperthetical** [peroju/dmtools_gammapy#7]
I am using `fluxpointestimator_dmannihilation.py` as described for the option 2 usage

I am using the latest gammapy version

I get the traceback
`Traceback (most recent call last):
  File "/home/geoff/Apps/dmtools_gammapy/Notebooks/point_like_sources/fluxpointestimator_dmannihilation.py", line 113, in <module>
    dataset_empty = SpectrumDataset.create(e_reco=energy_axis, region=on_region, name="obs-0")
TypeError: MapDataset.create() missing 1 required positional argument: 'geom'`

**Comment by Hyperthetical** [comment]
I also have an error that occurs with the first plot

`Traceback (most recent call last):
  File "/home/geoff/Apps/dmtools_gammapy/Notebooks/point_like_sources/fluxpointestimator_dmannihilation.py", line 83, in <module>
    spectral_model.plot([(emin*1000)/mDM.value, (emax*1000)/mDM.value], energy_power=1)`
`File "/usr/local/lib/python3.10/dist-packages/gammapy/modeling/models/spectral.py", line 412, in plot
    energy = MapAxis.from_energy_bounds(`
`File "/usr/local/lib/python3.10/dist-packages/gammapy/maps/axes.py", line 578, in from_energy_bounds
    raise ValueError(`
`ValueError: Please provide a valid energy unit, got  instead.`

**Comment by Hyperthetical** [comment]
The above uses gammapy 1.0.1

Using 0.18.2 I still get issues
`ImportError: cannot import name 'DS9Parser' from 'regions' (/usr/local/lib/python3.10/dist-packages/regions/__init__.py)`

**Comment by Hyperthetical** [comment]
The fix is the following:

A conda environment with 
python=3.8.16
iminuit=1.4.9
regions=0.5
gammapy=0.18.2
gcc=12.1.0
